from index import index
from degree_list import degree_list
from program_details import program_details
from program_plan import program_plan
from program_plan import delete_program_plan
from program_plan import program_plan_to_pdf
from add_course import course_listing
from add_course import add_course
from program_plan import remove_course
from add_course import back_to_plan
from program_plan import new_semester
from program_plan import fetch_dependent_subjects