from index import index
from degree_list import degree_list
from program_details import program_details
from program_plan import program_plan
from program_plan import program_plan_to_pdf
from review_page import review_page
from add_course import course_listing
from add_course import add_course
from program_plan import new_semester